"""empty message

Revision ID: 226f05d30995
Revises: None
Create Date: 2019-03-01 01:25:33.748721

"""

# revision identifiers, used by Alembic.
revision = '226f05d30995'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('mobile', sa.String(length=30), nullable=False),
    sa.Column('login', sa.String(length=30), nullable=False),
    sa.Column('passwd', sa.String(length=30), nullable=False),
    sa.Column('avatar', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('login'),
    sa.UniqueConstraint('mobile')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer')
    # ### end Alembic commands ###
